#!/bin/bash

OUT=/tmp
DOC=doc/hover.pdf
RM="scripts"
FIND=".svn"

BD_LIB=${BD_LIB:=$HOME/lib}
BD_LOG_INFO=1
BD_LOG_WARNING=1
#BD_LOG_DEBUG=1

[ -z "$BD_TMP" ] && . $BD_LIB/tmp.sh

SCRIPTS=$PWD/scripts

[ ! -f $SCRIPTS/dist ] && log_fatal 1 "not running from base directory"

tmp_mkstemp TMP
log_debug "working in $TMP"

URL=$(svn info | grep ^URL: | awk '{print $2}')
BASE=$(basename $URL)
log_debug "URL is $URL"


log_info "checking out ..."
cd $TMP
svn co $URL > /dev/null 2>&1

log_debug "checking folder name"
echo $BASE | egrep "hover-[0-9]+\.[0-9]+.[0-9]+"
[ $? -ne 0 ] && log_warning "folder not in format hover-x.x.x"

if [ ! -f $BASE/$DOC ]; then
	log_info "creating documentation $DOC ..."
	lyx -e pdf $BASE/doc/hover.lyx >/dev/null 2>&1
fi

log_info "creating ChangeLog ..."
svn log $BASE | $SCRIPTS/gnuify-changelog.pl > $BASE/ChangeLog

log_info "removing files ..."
for d in $RM; do
	rm -rf $BASE/$d
done
for d in $FIND; do
	find $BASE -name $d -exec rm -rf {} \; >/dev/null 2>&1
done

log_info "creating archive ..."
TAR=$OUT/$BASE.tar.bz2
tar -cjf $TAR $BASE

SIZE=$(ls -sh $TAR | awk '{print $1}')
log_info "archive is: $TAR ($SIZE)"
